definitions:
  dto.CreateAccountDTO:
    properties:
      currencyId:
        type: integer
      initialAmount:
        type: integer
      name:
        type: string
    required:
    - currencyId
    - initialAmount
    - name
    type: object
  dto.LogInDTO:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  response.CommonAccountResponse:
    properties:
      currencyId:
        type: integer
      id:
        type: integer
      initialAmount:
        type: integer
      name:
        type: string
      userId:
        type: integer
    type: object
  response.LogInResponse:
    properties:
      token:
        type: string
    type: object
  util.BaseResponse-any:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  util.BaseResponse-array_response_CommonAccountResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/response.CommonAccountResponse'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  util.BaseResponse-response_CommonAccountResponse:
    properties:
      data:
        $ref: '#/definitions/response.CommonAccountResponse'
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: API for Spendtracker
  title: Spendtracker API
  version: "1.0"
paths:
  /accounts:
    post:
      parameters:
      - description: Create account DTO
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountDTO'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/util.BaseResponse-response_CommonAccountResponse'
      summary: Create to account
      tags:
      - account
  /accounts/:
    get:
      parameters:
      - description: Amount of items per page
        in: query
        name: itemPerPage
        type: string
      - description: Page number
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.BaseResponse-array_response_CommonAccountResponse'
      summary: Get many
      tags:
      - account
  /accounts/{accountID}:
    delete:
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.BaseResponse-any'
      summary: Delete account
      tags:
      - account
    get:
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.BaseResponse-response_CommonAccountResponse'
      summary: Get one by ID
      tags:
      - account
    put:
      parameters:
      - description: Account ID
        in: path
        name: accountID
        required: true
        type: string
      - description: Update account DTO
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.BaseResponse-response_CommonAccountResponse'
      summary: Update account
      tags:
      - account
  /auth:
    post:
      parameters:
      - description: log in DTO
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LogInDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LogInResponse'
      summary: Log in to account
      tags:
      - auth
swagger: "2.0"
